### PR TITLE
Move completely to go15

### PR DESCRIPTION
**Pull request by cgclever**
For context, see https://clever.atlassian.net/browse/INFRA-1112 

This PR was autogenerated. @nathanleiby  you were chosen as the most active commiter of this repo, please review and check that builds still pass.   
Some known, but difficult to automate, errors are: 
  * In the Makefile and test_drone.sh, performing `go get` on the repo while it's now only necessary for packages such as errcheck or lint. 
  * Makefile testing vendored dependencies (which in turn tries to compile them, oftentimes creating import errors).

  * Dependencies aren't compatible with go1.5. For example appasaurus ran into this with gopkg.in/mgo.v2 (the solution here is to run `go get -u gopkg.in/mgo.v2`). 

If there are any problems, feel free to ping @cgclever for troubleshooting. 

For understanding Godeps and vendoring see [this doc](https://docs.google.com/document/d/1YZg2S7v1bir3MG1YvswAD2Y0KrsuDr-NCr6pPG2ycEM/edit#). 

Thank you\!

### CODE REVIEW

**Comment by nathanleiby** [comment]
Tests are actually failing. Need to investigate if they were just unreliable before, or if go1.5 has somehow changed behavior

e.g. 
```
batchtail_test.go:119: Expected output:
		'/home/user1/asdf.txt
		'
		real output:
		''
```

**Comment by cgclever** [comment]
@nathanleiby: This looks like one of a few cases where go 1.5 simply has different behavior. Will look into it.

**Comment by nikhilpandit** [comment]
hello! this PR has had no activity for a month. @cgclever: do we have a plan for how to fix the tests?

**Comment by natebrennand** [comment]
closing in favor of https://github.com/Clever/batchtail/pull/8

**Pull request closed without merging**
