### PR TITLE
Use Go 1.6 in Drone and golang-version-check.

### PR DESCRIPTION
**Pull request by peggyl**
You were assigned as the most active recent contributor to this repo.
Please reassign and share the joy of Go 1.6 if needed, or ask in #golang
if you have any questions.

### CODE REVIEW

**Comment by peggyl** [comment]
Investigating failed build.

**Comment by peggyl** [comment]
@natebrennand want this assigned to you or is it ready for review?

**Comment by natebrennand** [comment]
ready for review!

**Comment by peggyl** [comment]
Giving to Raf to review. LGTM but that feels like rubber-stamping. 😛

**Comment by rgarcia** [comment]
lgtm!

**Pull request merged**
